# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  filter_sets:
    # name our filter set "my_thumb_filter"
    squared_thumbnail_medium:
      filters:
        # use and setup the "thumbnail" filter
        thumbnail:
          # set the thumbnail size to "32x32" pixels
          size: [300, 300]
          # crop the input image, if required
          mode: outbound
          allow_upscale: true

    squared_thumbnail_small:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true
